--
-- ER/Studio Data Architect SQL Code Generation
-- Project :      DimensionalModelDemo.DM1
--
-- Date Created : Tuesday, September 17, 2024 12:47:30
-- Target DBMS : Snowflake
--

DROP TABLE IF EXISTS SF_DIMCUSTOMER;
DROP TABLE IF EXISTS SF_ORDERS;
-- 
-- TABLE: SF_DIMCUSTOMER 
--

CREATE OR REPLACE TABLE SF_DIMCUSTOMER(
    CUST_ID             BIGINT          IDENTITY(1,1),
    CUST_NAME           STRING(50),
    CUST_TYPE           CHARACTER(1),
    INSERT_TIMESTAMP    DATETIME        DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIMESTAMP    DATETIME        DEFAULT CURRENT_TIMESTAMP
)
;




-- 
-- TABLE: SF_ORDERS 
--

CREATE OR REPLACE TABLE SF_ORDERS(
    ORDER_ID            BIGINT            IDENTITY(1,1),
    CUST_ID             BIGINT            NOT NULL,
    TOTAL_AMOUNT        DECIMAL(38, 0),
    INSERT_TIMESTAMP    DATETIME          DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIMESTAMP    DATETIME          DEFAULT CURRENT_TIMESTAMP
)
;




-- 
-- TABLE: SF_DIMCUSTOMER 
--

ALTER TABLE SF_DIMCUSTOMER ADD 
    CONSTRAINT PK_DIMCUSTOMER PRIMARY KEY (CUST_ID)
;

-- 
-- TABLE: SF_ORDERS 
--

ALTER TABLE SF_ORDERS ADD 
    CONSTRAINT PK_DIMORDERS PRIMARY KEY (ORDER_ID, CUST_ID)
;

-- 
-- TABLE: SF_ORDERS 
--

ALTER TABLE SF_ORDERS ADD CONSTRAINT FK_DIMCUSTOMER_DIMORDERS 
    FOREIGN KEY (CUST_ID)
    REFERENCES SF_DIMCUSTOMER(CUST_ID)
;


